### ISSUE TITLE
Python3 compatibility issue

### ISSUE THREAD

**Issue by darkdawn29** [BitTheByte/YouTubeShop#12]
`

$ python yt.py                                                                   Traceback (most recent call last):                                                 File "yt.py", line 2, in                                                   from lib.auth import GAuth                                                     File "E:\youtube BOTS\YouTubeShop-master\lib\auth.py", line 4, in          import execption                                                             ModuleNotFoundError: No module named 'execption'
--

`

**Comment by BitTheByte** [comment]
Can you give me the ouput of this command?
```
$ python --version
```

**Comment by darkdawn29** [comment]
python 3.7.2

**Comment by BitTheByte** [comment]
I've updated the codebase now to support Python `3.x.x` however i'll still recommend to use Python `2.7.15` until i make sure that the codebase fully supports Python3.
Shell we close this issue ? 

Thanks for contacting me and letting me know about this issue.

**Comment by darkdawn29** [comment]
as you say , id go with 2.7.15 , and thank you <3

**Comment by BitTheByte** [comment]
It's not the same issue the previously mentioned issue has been fixed.
You need to install some libraries in-order to make this tool work 
```
python -m pip install requests
python -m pip install colorama
```
Let me know if that works for you

**Comment by BitTheByte** [comment]
Closing for inactivity
