### ISSUE TITLE
Becarefull , you missed one important thing

### ISSUE THREAD

**Issue by axel578** [BitTheByte/YouTubeShop#14]
Your bot should integrate the bg.request wich is the most important of all , if google sees that you login without it , he will wait that yoyu connect like this with all your account and will all shut them down ( i happened to me for 3000 of them ) , bg.request is part of the botguard process developped by google , it 's an enormous javascript script that generates a sort of sentence encrypted in Xtea with the key integrated in the bg request , the bg request contains your canvas identity webgl ....

**Comment by BitTheByte** [comment]
Hi @axel578 

Could you please rephrase your comment? as i'm not able to understand it properly.

**Comment by axel578** [comment]
botguard , the request you send should contains in data bg.request= ... , the ... should contains the bg data , those datas contains everything about your computer , if the bg.request is not here , all the accounts who send request without this bg data will be traced down and terminated .( closed )

**Comment by axel578** [comment]
the idea know is to reverse engineer the bg.request wich is process with this script :  https://textup.fr/313569za , to see the bg. request, just go to youtube/upload with the network inspector of chrome or firefox open (developper tool ) and upload a video and catch the request named ...rupio?authuser=1 , there are sometimes two of them , one of them contains : X-Goog-BGR: !4eKl4sNCyy... the goog-bgr is the botguard and after it is the encrypted text containing all your computer information , this encrypted text is generated by this script: https://textup.fr/313569za , just know have to reverse engenire it .

**Comment by BitTheByte** [comment]
Hey @axel578 

Thanks for the clarification I appreciate it.

First of all i do understand your request but unfortunately **I will not fix this issue**.
I created this repository as a side *fun* project so me attempting to reverse/crack google's anti-bot protection is over do, instead of i could provide a another slow but reliable solution by using [Chrome web driver](http://chromedriver.chromium.org/getting-started) For those who want a reliable results **But** using this mode will cost alot at the side of system resources since running ~20/30 threaded chrome instances simultaneously running Youtube will eat up at least 4/5GB of your RAM and probably 30\~50% of the CPU *if it's a high-end model*

Of course any better ideas are welcomed so i'll wait a 5 to 8 weeks before implementing the **Optional** (ChromeDriver mode) just in-case anyone has came up with a better idea

**Comment by BitTheByte** [comment]
Sorry for the delay. After further reviewing this i decided *not to* implement the suggested fix.

**Comment by ikp4success** [comment]
if you go to any youtube video link like https://www.youtube.com/watch?v=AV8GNQTOyBU, open the page source, there is "botguardData" in the youtube source, if you ctrl + f. If you can manage to regex out that data you can use that botguardData to login. All you have to do is make the request to random youtube video and regex that botguarddata before your google account login request. I am sure this will be blocked soon..lol

Another way is to try and sign in with a fake account while inspect element is opened and pre-save bgrequest in file or list, dict(do this process again till you have enough), and randomly get bg request from list/dict/file for acoount sign in. Bg request is persistent, but expire after some days.

Another way reverse engineer BGrequest..lol

**Comment by ikp4success** [comment]
if you go to any youtube video link like https://www.youtube.com/watch?v=AV8GNQTOyBU, open the page source, there is "botguardData" in the youtube source, if you ctrl + f. If you can manage to regex out that data you can use that botguardData to login. All you have to do is make the request to random youtube video and regex that botguarddata before your google account login request. I am sure this will be blocked soon..lol

Another way is to try and sign in with a fake account while inspect element is opened and pre-save bgrequest in file or list, dict(do this process again till you have enough), and randomly get bg request from list/dict/file for acoount sign in. Bg request is persistent, but expire after some days.

Another way reverse engineer BGrequest.
In python
https://github.com/ikp4success/bypass_google_bot_guard

**Comment by BitTheByte** [comment]
Hello @ikp4success,

Interesting approach, I'll be taking this with the recent open issues in consideration in the next release thanks for helping out on this

**Comment by BitTheByte** [comment]
Hello @ikp4success 

I've been unable to bypass botgaurd using your [python code](https://github.com/ikp4success/bypass_google_bot_guard ). based on my knowledge creating a successful botgaurd token require some form of binary which get executed at custom javascript VM and return the token I've taken a shortcut by grabbing the binary from the page and let chrome do the heavy lifting. I also thought of getting as many tokens as possible and store them for later use but if tokens are verified based on timestamp or has a life span this will fail. I'll be researching this more. let me know if you have any ideas

**Comment by mewtlu** [comment]
Hi @BitTheByte, sorry to necro a fairly old issue but have you gotten anywhere with this issue? I'd be really interested to hear whether you've found any methods of getting around Botguard!

**Comment by BitTheByte** [comment]
Hello @mewtlu 
the bot-guard is actually very complex and many factors can effect the token generation process also google now uses more parameters than before which requires many requests to different endpoints. the login process has gotten exponentially complex don't forget it's powered by AI to detect any unusual behavior so even if I found a bypass to the botgaurd and a way to login I still have to deal with the AI. I will continue not working on this project until I found stable way retrieve cookies by email-password login

**Comment by mewtlu** [comment]
Ah okay, thanks for the info! Will keep checking on this repo to see whether you come up with anything, interesting stuff!

**Comment by nilaydzya** [comment]
Getting this error as soon as I run the yt.py
[CORE]: Handing off botguard.js execution to chrome
[45060:12812:0529/223315.113:ERROR:configuration_policy_handler_list.cc(90)] Unknown policy: Quicdisabled
[45060:12812:0529/223315.286:ERROR:configuration_policy_handler_list.cc(90)] Unknown policy: Quicdisabled

DevTools listening on ws://127.0.0.1:56628/devtools/browser/7e9c6680-fd4a-43e7-aaad-542fb337b9c7
[45060:12812:0529/223315.441:ERROR:browser_switcher_service.cc(238)] XXX Init()

**Comment by sodevrom** [comment]
Curious to see if anybody knows how to transform the "programdata" variable that we get from YouTube to the final request.
If you try to upload a video for example, you get a script that looks like this:
`{"program":"DLB2YySmiIdSeak5DNP4p7n24iJVanhQwCYuZ179EihOWz9nRMXw\/gBbH8RJX\/4IEDkky6\/52A9pC8bdJikj78XL\/lfPvOkSQhKern+gE9qN6RRB5Mk3Moej\/OPI4ahFW5jxBKDZfSDwuDPewff\/HR3np+SUodSN7zdVlQgt1btvr5jd1XqwuXmTXxoYEftBd7ie0BjF1vZV6BrSNSik\/jVTzl7MQqxI8BzlSMvv00Cm12uAUHeHu2pBz\/MHqD8iz9yBgzPhx964g6LCu8gZuuoZ+zGf+dpJvEnqNngvWlJeWyKG3j5mGDb476Q\/H6PoHiHCoCE5dZA6ZwIWEFcqxaAhvIm8vVsnwLEipjP5U2tDTaNpL2A24kBcdvKQob1OZZF2r7ZX53WSGIRn\/acPRmZTcUOnCETmMAkkdw5lsXJPpZ9DvbXJiT6HtVOGTiuUIJa0piHNYnKboFnGlX\/VIqtxi5Crdnym\/AMSUl0sIa9jtRoGQ8F45tDakTlmAUjwuG5Qpk5GSAa7lAmaK+46OfwXXpgatmYgW8BX21E\/Be\/Vq0EdA0Nl2IhBLAnvaF3o6rZP6IYfKdSSgiIdKE33yg9qtfq1LtJ41CgWzHFO2QBAGxhaS7NcIJWwx\/nZw12s5a7+KALupW2V2JdNV8PkdcOKE3+QRFFXht+vka4jwITDE971YcgtXfPqycCUD+lzFPNLTK6ecWj+hsWOSBVi8YsAaZah\/8k\/OqFIgH7QcmaBggATA+C559hGHZMn\/b9dC3PtSmGJnkqTga68FGrt7uCm6HOUc72lPz7qq+NCoLZqNeEq0P9LQgRYIFB9jO8Nh3i0pZ2xj4IWDIZC48FokYBstskEcAYuqDHoENF2S\/22U2UVoNLDXVsR2NW5MgJHBwJdw+7exhG+OJ98gPaGIvTm\/Vt7NLp1psrWdAmW7Mgr35sP6fW\/nw\/KDxlcWRY\/E2LhQSRwuv++O3qDhyaMxPiJZo52yyuViai+hkYXTYW2G3DUYHKgzuEBKnItofXMK82POfgBVgowNd8s1lS1vBWgpaKYl3R5gWkKFnoBhXokKsSsKQYAutT7boKwHAKt+z6kYEydLtffthO1C3RoZRrPtSxHUXs1iuuLEERss0JomvYzhQz88LE8VYp8vZCJR8NlHZrgyQ1Cx9jUg8drJ99hMkOBe\/3lEvf\/e9Pr3Fwt28Y2WEH6R4Slz\/GjZe+HfByuAW7N9WqUzjLcZhOOz6iH30QHqGf6tJXRptWLyZFSRGyd4+VdGBdG\/ARWcTmRxlPlG0y\/Si6Nf7tvu4hMii4z4EFi6RYSUxOXvZZnwFsZoJFwyxTZNTmdODC9ArmlJpXx+dCU5zxN9q0LtmmS9QIeCc4IqQVmXGzU3uFOy+rEDJhLP2A0yYOnZcfROiFRkoxdtQIWA9TgZ3dhIuXdqehSiFzAuAFW7OHYqgiWtrOAy+1jhydOtn+mi4isz3QcmBsLfO8RwjxFSkLG9OxT4RGzc3rokAtTorexkZDyLIZnUr335zSW08wORVFsLqU+wxd9HbojEBj95zp0dGtaW0T9G89PNE+dPxTuH7AWzC4zF2gehLnjeVL3mVha70tL5dXE7lwCwYyMollwKDZk1Oxohn4zO4AJPV+53irlub\/9\/5DxnOmXcNSU58ZrU3Afobl5uKuVbnyX8DV3mHQXvh7I4PS3zzNsyPmFlwgdxajDftHNIYX6aliop77vLdE5MEVEJ7Tt2a6yvuFmKSCnWUfSpsy4bsE32SJfMyRArDEleZRWBY0nB1YxRp3ZYmCN\/AjUOrE7PpGU5znZXJE5MpLlpEGaSfLtzB9Dd\/xm+qcoCdOdt97NX+dTyPwOaSf33TY+MAbu8bHOiLU2Rv6XyFYuUr+K5DlexI7fhsforLdPjGDTCFQDRUlqOPha+tLA655rPwPoZK85a3mvsCKudKk5pz25pO8ePx39p7jeNG74SH4fYBUmcKXvXz9u9d4y+DgeNVQioBoSCytC1ZPe1qRowPe4Mze7JubkpQy5ERn27HENda0B\/SmIA1StwklqXigBScMRcq2BdXbX3gyNl\/f\/qUi5s320Q\/vJ0nfB1FB7JaoiqaJQC+ET58ckCk7Dbeb\/XshEe8JBX4yjsFTrKq9J2nd\/i\/95aaj\/B6\/YpqaJrI3YFq+ZzGsj5h9NALyBYdgVgBTPfR5y1j9EOB8a+tkmPJnuewey5Nwoz49QEBU\/Iu+IyrOwiPnTiqQFqqHDoOLjz4TL7aoQ4OOcGJERx6gfdV4J3Y80rYKO2yyPg+1ARwSS2MujYxftz7lSazKdk1Napxcp+cRlPzsbHwymhYLJH\/Eghw2p4bU6RRtU3jVWxHr\/6AeXjbOKZVLSR7\/TzAozLfEcUnOMqQqjfDOBJYvOR8nYtbwLCu+J6OWcuAyEfj3siMXx2v3DY6JLixj5Qiac\/ICp7QxSZP9Qn8CgUYoN6S+02cYuD9Srot2RGGfVqRoJTMvCKgAY0zgx+2+yDEDnetDL3tVM8wt5ur96gHfTNshnJKSXCwEG0lvmuzxCErIeZQqu+29osufGhinKOVA6bOq5ClmoeLJTgR7YoljJdr4LRDVZmqgclKvl\/5qZZyRtQ5fH9Nna57jcXLPBxFXJM9P9XikmKV2Xi0i97MNtBfFiTGq4\/ZXBvjsAsKpFJDwE5HQKq+S\/0b1zF+YB6uGZ4Qv\/BESaxGyDbZvwLt61iB3xYgvTABhkD5\/hc4udyzIGw+3489gzMAhlHAEWJraPQgjByME4nYWxiBu0alLukPfmP3NP7xIh6bLsb9aWMjOvrx5UovK3c+zqneBsZMU2A+Qc4tMNTUznjPGm2QFg9EiaWj5k9qks86MXTyS4hTPaX7U8hShq+XBLtWSCls6T8tBfS\/QXlHa7vTrKKCUS7CFJceSzb+YDlD1YWVfSx14IO71A+y89KRa5Wkq7x0WgIiy24HnIXfSHmV2om53y7AAwEez5DjSetVcriqttoeVAKpnRwH8MavK7P8IidUy8xVPNkvGvY78L0xI\/28L0KM1igPUH+avve752p12utzumVP84l7dvosb0r7cq5zskapMpx97WjR2M36J3Hxu6aDUsyJCMobzWyn5tImsLDUQ48xp6tRH2L50pfmdWXId6P7Z5GyMftB7puAM8UbxSHHW4dLv6F5JDDfkUsVB2zBfWtsSfdJdaOPKvwuxhrAtt58CJYRk8cyMrO6TD7OPBygHmKg4QeX78ectmWj8oU7eJYpZlsjYKmty+PWTTaxPtbvcZngGcSeJiWFgMAd\/Wt8zMUZdXl4viXeYAGzz77azUzkJ9FCaZQGL\/025mR80RAd4iKqzk5qvoNSYJq9W0qCxN+uW8jGWbVl7yMjU8mLI376f81xInFG4WV7slebqJ9Iv7HTki7p\/bKDpph26IMSP\/ib37D5biu6yfT\/xoVcs\/0+3DEU1EeNU4eJwN2BV022S8nEjHaeSkxubwAeeLoLubqtHdZ92VSiobZwev6OOC9TFx49nIb6k9SUMykmauLtQ2+NOtD1IiCyPAu+3e6XKKkAb\/r54x\/+OetGwSIFH+SCNmVcjK9qxktOAr0oHh9zu7kbcW4RmKSvqNgIbg39QhNIzvVkWjOM3uIifgImTfYResujNCnQD3wj7KexX5qxQKAV0MNr1Pj8q+t8WfTFYlt0p54uZF9u+2QvasJivnbnRWw1Qwr5Timo2kHIJAC6j+9Urlfoz73hRcRMvcqfpnsvDCTvlvC1Z41F+ZjPyfPuXyVb\/VKcSqRSfWF8U5HAG6+jk8pzJ\/CGGTVylNH9mhTPpKG3h2IbgEpK4k9PeAxtjpg9U58mPfLnY+tsHYLwHuI4HIw8RVuRAzmS1wM7+W0SAtXxQZZmDjIqthb0rgMve6jqXckPjTXecorRsyoHRkLWTod7H86rfqAqYpYMolyx1Qz2vxYQ2IDhzG95aSS7RPqBk4paCYjVEEJ2ul4gd7y6mP8HLVKrdkKhoy1C1OrDwxubXy8k+ZD6D\/b1eyGpp0Wb+yke3mT63weM9DzTa4w3pE7smRVEXW6qxHBN6p3YjLUno9Oj+uiDto1pTYhkBNmMUljwcItbvsEqW7gokygoQUg6DnWk3GIWfhtEjVNq9PG28oK6Lvq8mpq3\/k15t326V6u4YfdTYmb9X1qVTMPYDpi8vuthO43TlMmDDuTUiGVegodLa9h6HYqelbPwHUXG+sZUtjIPyyHXMnMxosR4pvdmoSLtaYvxi9fGcZ5t8g06GdVRAEMyFWC2BZIh1Rvh\/OmbxRQb1hEj\/8NSk\/OqHOdK4dR67AUXrWpcC8rMBDyXopcdsOM79CdDAMaxetuPlO9TwgNVWTGLQHg4fqKHWO1DJMpA4b32cJupWDoU\/Z7oGmRLLzcpt6P\/ia2ycmqCjJxHlqrs\/gMY6CQ7NW1uTcSPskOuhsTwq22UXYBtleCpe9+gbLVqjQfv4FB0ChzXAw1l57H3lJqlUzEiMUV4InHYSbd5FxHEqnzWdenQIWQbMatBzMMcd2iCmKPb8Sp\/gYvnbx1MdaSR11214IPri+RWKeHD6VkVSmA+UDtT2sm0k9hKU6g78\/OOIV2s6V8uJz5PdApM05ZFZ5JsTxFYwEPeAeWxtf\/\/2Y3UqG83X+Qqslrs7QCTf5F2ab2tcE2QXVQXdV17xcBdG1bo6zjtjwtTv71axdwAST83YJX8OQLNNv9HuO+2\/0pmrQe0Q7LEJgginkCJE9cxH8q3+yZnK9v5j4XacCMYQt3TTdJGwWuBQVQURo+uvAhvb1LpGZ8hFE2LMHUD8MwrKGLgrlrCuJkqFXnqcf9ZJID20HcY8na8AmRqXLuiuRwg6Wx55PhNwugclDefJjnOvgI52XBoSnL0dz17PbZD\/eDXgNh44J+VIvnVbFPkaChBmTZgrk8lSOi52ei0Njz800fahMSXHt+9gdRaKec6PP\/H59aFH5LFZ4kTwTpS61bzL9jbHZIbkqEyS2m3UeQlQT3B8LwYVOq\/E9Ha+W\/uCbXZGbRCkaugmZnqMQaDVVZi36SNC02vwp+jLWkGhOQMKJMu8hPgnC5nJlJNA81X2OcNtbMG1uWNw1BFjONv94GRkLEOv2FFkB2aTmalZPnfSwSqyJFc4ZOWjMYE5CtD\/\/IOpDC4hBqodYIReHWHT4e\/Pp2SN\/2uBy23fYtOHcE2hDpHCzdUEiwi7yGW38DTPn\/O\/T\/mnjMnd4uTdbjveeMlhSVS3Kw+7awAdLdzguH4ICfJ\/\/2WC9xSW840ppKwhNjZ2BtE5kSyZHT2\/RhmaTYzfG98mPTjvoeOlKgwEk\/HvyTEz\/xOpwqVKdvw\/Gq62Ps9\/\/ME1v\/kg76IImuSt9aNV8yNUzrWbS1OaXedy+knf9CMRXg2a9FUmNHlermHsuRX41DJEsSa3INHzlx+KC4yo8JanAKlaJ0K81Et6mCLC6CkfVc40oe0lcU2hy8zDaZZ7KTjRdmrtY9\/yYozq4EM9xowyRNU4q7tzRu3BpxC7HwmnRhSqnvs+AnW3frO\/GkJOXJ155pSrGaxNIt7VUG1zeJvnpzL+U+t7qAkly5W4zMCKFF9r2FzNRiinA7HIODaXsVZRpwbTrliWsbiKIIXE9fLYc6Krd4ataIPAoxwTHGLU8ghc6Kxoq5FPng+a3KdSkIGgJKGndoBdJcGdynpQtfJAI8w6z8wBHzeb2POguQLYWyoR1Lku7o06DuaJVbFJP0RAVbtJaBgFKYGrzL3990MrAmF0\/IYk\/o1r0ONz8q3tikvh++FNT0w0kpOUmpThXZD7JvcG5IGQF8Map+54egCQjUThd4M8\/dWR64MtR0+l+3lMJqtljPk2fHLLS7TxL\/45WdKC4D3SPUuqYtwSRoFECHMZc\/N80yB5AlJffmKLlus+FBidXvwB2sf8cxELWC2WlOmhnkxMGnV4caWN0We8Ef4z8LHekduJY5UWHZRrdkBdyTRiDs3MWy4gCoRILarC6bSgtE52VTyaQRNBfNpaas2mJNiHl7uwXQb\/A4kCJS046H+0oVCEwkE1ALJBn+NneDAJXT6yNnfl\/t7MznMwZlUFHAxNA+WhOHthZnaHqIRuoABBqedrfJEBKDVY\/jvpRmWO3x+L3dtDQs2ExBHR1KwV6fUptEtJuNy9KtSBEM5Qgy\/oP7OWQpJ++2Fvol5Tg\/Fm4Q+TRsNfVUqFigOEMD0FnYBzOwpvxQULKszPvflIa78wv1ueCnK6HwnDo96IPk9Fwj7LVXwfhAwC7Ftw\/xZiLuWXcwTaVe2P4DYO2VaHiacdOCdgmXTYaUfeLg19nz++GFOLb2YRjhopxkxx7TXXbeDL6F5rutyq2Fr2ES2ASoXJeJy7dxYWbvDzZ8Ijd3JnkhuCNAs8VzAYwHrdStjSxmmM7cBkPRzvpfZNtkARJ+8p7ghWrBlALgwFqTy+fxG5twL9t\/7UiFrjyIu+ggP0OVBTVAg5vKt9hgMpew9ZlYC\/1lcdKN6NeJayV+GEGb7eqzWy4N8w9b7D97u8S5Ba7LUhylFtHoOFDJu5ivFAl45mUlJnUXiw+O++l7ECYaWAt6\/XsueSS5164IonT8lIPO9ulztBG8RrDQsNrRjaFkQjwtA6tbFuR5ke6QHsABfaKZDOivGMjfuCRqPn+mnS0Xv41n4BnYxPo40tB5tOkrpPqqUs45yflutJAEC+25hVoP5dR6DCTN0gh23XIwJSN1qWuhCt2cwkyCudshh\/Cx4hr2mQVDbM7C0BYOL5ZDKykZAcOi+zXX5UhAKwn2j6105i6m3abIvEIyTkCVwmpOEUuGfPforCx8sFTeR9s1cLCUmvYKzA\/aWsnKkSH\/p+Dmu3Ce297ww5acz7uoc3jaKS8+QscJwunjwdXz1VzuEp+01oMNAOn9TadRcohVuFaKk923ySSer406UGgUz\/uxaEiQoZMyzjYMiCBIynX+JdAwOMtOdUJ4YWpRvY\/cb17rhAswvYuXrHOIrDtQ88zCoANiTJgdPruUKEf81pf5xsWzKk86CQLszx+YW3T++e4qNQl9TX3rDb40cEcW0WLagUqM3mXFZgqeGbG82MKh15+vnGwM0X3SeEeS514ej3ugNKli+vaomF+9W7llXySx\/CsGgPjbG0oEc25MRb1IprN8HYR3klt0v\/UfQJRQ6hFxJnl79xgMTYuZFvZp99zV8X+6LW\/vW\/0X+nikvZj4PvZBLrLeNtSQpCeAYgQxWMyUUjsoZkjjkNJ4nftpY15MRf9QF2tiQersQxzQcNH7cSxrAIQsFTVtAFsRZrbO77O7CTdn7EG70TLSDQcnVR2eyO0Aw9byYy6XzIYI2PoAegml\/Pf3lEI8ZbJPTZp+\/IzTIwEqU40CkRs6dvaY1mzRHxBV1KQoYCgXsHEvHWF11IytHgWcUFCtpdd109vZq\/SIy1g5tkifgJPL4EyUIrgUuw4SPS7zGayfdDLXrAFCuKc1PDofmyaJWOx4hn8GXOpave6xicViJxwa4kmK458Qyeq3xBEHSDe5Eqp5uniwc8ak\/CwapQ2B4XSB\/TV0hLwKGi4jb0R3UV4VCOfrR0hej\/ZzfCvGD4OaudSAnuuDpkGSxrB\/oHgK6WMku3cWGch6hlLQ36W1ObfB8K\/Ts3iQBTO06DCDo5Xq0\/\/Mk8MKVLWMeIwfD+bdYTIk33Sx0awDb+puDlJY1R4bKgyPcUMTmXrz6VOETi7bnKxN14NERrzHsTJUtsynhsLt81oFyeosxtNopz\/QRJKEVQy7YMhFPOgJY9jyMsYO8oPT+OjparYS8ZkrbEBrpeh7F+WXOsPygH7xk+kumRA\/YVwWuCBCcR6HZIhtFvb4u1nnH0JDjimo\/Lha6Xa9FODNeujoZuRVAvFMFEsDM4yZx6lAWh9xW5cefbA0exwUCN56t48QhYOmE9cFCKG1\/Qbga9TSdzwTIItP9oRDlbqt+18Q0jw7Ckf7vJd0UNmEA7zgYbl31Ay\/V9jwYcu4WKJShzphqwqmoEf4nSyaI4gCyabzfgRlKTkzLTC1ZrglTQ1h5PJlNxc9jEj1yNQARIW60GgMglO4kwinAVrnRyFL80ce7dbLQiMCNwW90qdpcsqwTehnmMerOXQWD7LAVd7p0t2wwxAyeY8eLGmrWT4qpKbnGXxJEIX2uMmlr8HxMwbA9zouLm+FvmpnmgbF\/ljeL2\/c0Kd4cUpEApMwlYEPNHZCC1p+MEPjKYtwDThBC1GxXUIppNZlcNUsipPw2pxK0CT9pO1hY1CV\/7Bv8YXU3HtARH2LMtHvSWhaUUXFsm4+XVzHsjFYWqXokqGxYnvzANqRCpfovfM8ZGJ1lKguzhKsg5TgaJiAhisLWaCOS93ZPIjFtzN8bn1UdRz4X9QvdIbouYKIAygs0+ZIHxW2q1MjvKJ\/HhxDSw9+NU+kd4XkWtCWl8ksikUgDu5Z4wGj8yPJj\/WCzWIACcVS6JFiSswRyy3zg0cOjBYPQT\/BKkYhW9Nk03O2SMMjHzRX\/DWolydqZBPrMZPbQZIrNMUx3QzJRlI4yqmqcclnjHSHJcbDtyVmkz6Pfr3Zs6PqVrnNlghft8sa1ezCI3I6bVblO8NZUzEpqmQYTMvfOBlYej8iob3wakmGAO57ZO\/D0rIbFhNgEMqh+5Mgn3IlzlxwlxNR16NrlunwJ2Pd2wjE30tDnZScfkclRasjh1lpYaN0fG343qG1Sx6p6m8eBRLQcJvodHqNhkbC3NEGSS3ZJaD4CTODtz4ZStu5TPTaY66LYkk6Hex5zYZIVqCk9A55J+tisYlI9TTMmZ\/+kjWCdm8y14g9ZNICgJNA71GMAkPfdXjim1LSCNNJlbUqRzGEpjDsq\/rhNWYUk8dyr9b0Ap7sUpjCYoqeBGW0mzyP9pm3i8LqtHIVAK7rKY2i0S7x8vweORFgYPVmppI+\/BcktC9sqt1ZO\/Lp69Gk4yFDpVyESLHth7NLCxelj0LOHJALTe6+QCSOsODiLjOyCklnQp1yoOisTKDMi3w48KOAQtcWrxN81sF3WSP96m0SRK6ZwwRADghOuZlU2CvpGrLIgdtCvAQewevdlP8gv6pAK7HIOSpFPeQG\/7e6mJBpo9RGGn0+uGp2fmunAZ9s+SMTcjCeIIl1FLmeJ0HVFLKyRcXtH1xRLQJtHKeiACYGNk\/2mkNeeNdaEcWfd6HTr1seuNZ42rndTuMVDZ2ybdySBRSGt0Vim7kIQ25oJ5isVCIb0Mpyf+AF5LLpy8sTshhSnSGYonJAHAt5JHtIOlry1Qv8ShASaYWA2WAVpIljMxas9iOst3Ae\/3SurggkkbcLH1OumsrTIZRORdZ\/9KtbfO7M+2CnA0slX7KRDSg33zws+wcLH7EoTCObPHxxdXLTpi\/zfEcR7n1c9xWeKxMNqRfL0rJzS8z+aUYFQ9k79a+iGaLlSZwkya4zGWs9Hp1vnn2q9QsjtRTg2ewiaYAbWfmSmpC77UO0ryZhHqabB1ld5bcUiSEEXjobdpLVgZIfGE+XivBB5pJQHIDcICyxRw\/M2AWnV76+icl2dfgFVIBS+ZgHZLoQrmghQG87OD7qSiCJGFva9674uObWN3VacOGE3sCYk2kaNTwGu95NCh8rtIYUCtnjMVuOqqDwdkp9SFTQ3bSdQ9o9AOpto\/NsidPypLeeaxQHLFQXCZb1ggm7jHFB9Dolmo5QILjV7pwGydMyvEKBao+MVy+\/jjQTRR5aiZDiqNl0cLChkentRRBdDGVKw3wFpeEddhZrFAt02T6Wj0Lclrx\/CZ9SGkJk2qj40yDpDAHLaLJXnsccbSjpQlirrw99NubuZAv0JKFUth4\/t8ZsFbfcyT6zCgBfOv0WE6o+OgwNd\/NlwvTuZTvHZbtbHuPMwZGvsF3W4HYokwU9H7QIaA1hK3TUVaAH\/iX8mOfkG6Jt7sLGvL1Q\/\/L3l0c2NmcmFtZQ","interpreterUrl":"\/\/www.google.com\/js\/bg\/imtBY8ACr81PWsnimbKUgHx1eKHLlspVp9xQGu-eDVE.js"}`

We get programdata and interpreterUrl
Any idea on how to use interpreterUrl to parse programdata and get final string?

**Comment by BitTheByte** [comment]
Hello @sodevrom 

Sorry for editing the command since it was too long that's being said, I used a trick like this when I published the [temporary fix](https://github.com/BitTheByte/YouTubeShop/blob/master/lib/auth.py#L34) however now it's required to compute some other tokens besides the bot-guard one which is not an easy task.

**Comment by BitTheByte** [comment]
Just to let everyone know, if there's an app including web apps, Android or IOS that could interface google's API and could get **valid cookies** not API tokens from google I'm ready to reverse engineer it myself just make sure it's *not* just an iframe or webview and hosing google's login page inside it

**Comment by sodevrom** [comment]
Hey,
No problem for editing.
I am using GeckoFX c# to simulate logins and login to YouTube and then upload videos.
The idea is that I have been using the old YT interface to do the uploads, but now, YouTube is switching exclusively to the new YouTube interface.
So what I want to do is use geckofx to login to YouTube only, and then, upload the video via http requests.
I have the upload page that contains programdata for botguard, I have the link for the script, but I can't manage to execute the script with the programdata to get the encrypted botguarddata for the http request.

**Comment by sodevrom** [comment]
Wait... I think you saved me on this one. So since I am actually logged in a "real" browser, I see I can call "botguard.bg(PROGRAM DATA STRING).invoke()" and it gets me the code I need. I think it will work!

**Comment by BitTheByte** [comment]
if you're going to implement the same idea please note that bot-guard tokens are detecting (time, clicks, mouse movements, events) and feeding it to AI (which will detect your bot eventually) and are computed base on the browser itself make sure to add a bit of randomness to your program and use chrome-based webdriver

**Comment by sodevrom** [comment]
Thank you for the info!

**Comment by shahin1849** [comment]
DevTools listening on ws://127.0.0.1:64055/devtools/browser/79bc8f8a-e31d-4b61-95af-7e275e2e2547
Traceback (most recent call last):
  File "C:\Users\MTIL-PC\AppData\Roaming\Python\Python39\site-packages\selenium\webdriver\common\service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Program Files\Python39\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Python39\lib\subprocess.py", line 1416, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\YouTubeShop-master\YouTubeShop-master\yt.py", line 100, in <module>
    driver = webdriver.Chrome(options=chrome_options);
  File "C:\Users\MTIL-PC\AppData\Roaming\Python\Python39\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "C:\Users\MTIL-PC\AppData\Roaming\Python\Python39\site-packages\selenium\webdriver\common\service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

**Comment by SeanWoo** [comment]
Hello, do you have any recent bot guard news?

**Comment by axel578** [comment]
Dont want to seems defeated, but We should consider this issue hopeless since botguard is changing every day ( some sort of procedural javascript code generation on google side maybe ).Since 1st deobfuscating the code is just so much of hard work, but reverse engineering the patternt they use for their sort of procedural code generation is way harder to identify.

**Comment by akasheg** [comment]
> Wait... I think you saved me on this one. So since I am actually logged in a "real" browser, I see I can call "botguard.bg(PROGRAM DATA STRING).invoke()" and it gets me the code I need. I think it will work!

Hi @sodevrom,

Did this work for you ? I am trying to do the same thing basically, I have the interpreterUrl and I have the program but I'm wondering how am I supposed to use this two to get the final botGuard string. How did you call the botguard.bg(PROGRAM DATA STRING).invoke() as you mentioned ?

**Comment by thangtm0212** [comment]
> Wait... I think you saved me on this one. So since I am actually logged in a "real" browser, I see I can call "botguard.bg(PROGRAM DATA STRING).invoke()" and it gets me the code I need. I think it will work!

hello, can you help me this issue?

**Comment by sabriabri88** [comment]
> > Wait... I think you saved me on this one. So since I am actually logged in a "real" browser, I see I can call "botguard.bg(PROGRAM DATA STRING).invoke()" and it gets me the code I need. I think it will work!
> 
> hello, can you help me this issue?

can you help me how can i contact you

**Comment by sabriabri88** [comment]
> Hey @axel578
> 
> Thanks for the clarification I appreciate it.
> 
> First of all i do understand your request but unfortunately **I will not fix this issue**.
> I created this repository as a side _fun_ project so me attempting to reverse/crack google's anti-bot protection is over do, instead of i could provide a another slow but reliable solution by using [Chrome web driver](http://chromedriver.chromium.org/getting-started) For those who want a reliable results **But** using this mode will cost alot at the side of system resources since running ~20/30 threaded chrome instances simultaneously running Youtube will eat up at least 4/5GB of your RAM and probably 30~50% of the CPU _if it's a high-end model_
> 
> Of course any better ideas are welcomed so i'll wait a 5 to 8 weeks before implementing the **Optional** (ChromeDriver mode) just in-case anyone has came up with a better idea

oki i need to test it how can i test it , i try to have the bgrequest for the signup bage not you tube
