### ISSUE TITLE
Error comes please help

### ISSUE THREAD

**Issue by kirish93** [BitTheByte/YouTubeShop#44]
DevTools listening on ws://127.0.0.1:52772/devtools/browser/fa0050d6-fa19-4519-a36c-88f7de9d1e6c
Traceback (most recent call last):
  File "yt.py", line 94, in <module>
    threader.put(like_wrapper,[credentials[0],credentials[1],identifier])
  File "C:\Users\kiris\Desktop\YouTubeShop-master\lib\multi.py", line 43, in put
    for _ in xrange(self.q.qsize()): self.__t()
NameError: name 'xrange' is not defined

**Comment by BitTheByte** [comment]
#39
