### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by DrBarberr** [BitTheByte/YouTubeShop#45]
This is the error I am getting

Traceback (most recent call last):
  File "yt.py", line 94, in <module>
    threader.put(like_wrapper,[credentials[0],credentials[1],identifier])
  File "C:\Users\liskh\Desktop\YouTubeShop-master\YouTubeShop-master\lib\multi.py", line 43, in put
    for _ in xrange(self.q.qsize()): self.__t()
NameError: name 'xrange' is not defined

**Comment by BitTheByte** [comment]
#39
