### ISSUE TITLE
Unauthorised

### ISSUE THREAD

**Issue by moidwasir** [BitTheByte/YouTubeShop#47]
hi,
Thanks for y our code,
I am facing problem during login from email,
after running the script, a new tab is open but didn't work,
I recheck my mail accounts and they are working fine I cross verify my all account

![image](https://user-images.githubusercontent.com/6030023/76733583-ea262800-6782-11ea-8596-9d17444f5f5d.png)

Thanks, regards
Moeed Mehmood
moeed.mehmood@gmail.com

**Comment by seventest2021** [comment]
I have this problem: 
DevTools listening on ws://127.0.0.1:55712/devtools/browser/4bcc33a9-7cf4-4672-a6f6-33d127e15c9f
Traceback (most recent call last):
  File "C:\Users\tudor\Desktop\YouTubeShop-master\YouTubeShop-master\yt.py", line 96, in <module>
    threader.put(subscribe_wrapper,[credentials[0],credentials[1],identifier])
  File "C:\Users\tudor\Desktop\YouTubeShop-master\YouTubeShop-master\lib\multi.py", line 38, in put
    for _ in xrange(self.q.qsize()): self.__t()
NameError: name 'xrange' is not defined
------------------------------------------------------------
can you help me please .
