### ISSUE TITLE
YouTube Shop Error x(

### ISSUE THREAD

**Issue by ES-Nighty** [BitTheByte/YouTubeShop#52]
When YouTube Shop connects to DevTools it says to me this... Please Help bro x(
Traceback (most recent call last):
  File "C:\Users\Mustapha\Desktop\Nighty Programs\YouTube Shop (Likes, Subscribers...)\yt.py", line 26, in <module>
    server   = botgaurd.server_start()
  File "C:\Users\Mustapha\Desktop\Nighty Programs\YouTube Shop (Likes, Subscribers...)\lib\auth.py", line 16, in server_start
    self.browser = webdriver.Chrome(executable_path=r"lib\\chromedriver.exe")
  File "C:\Users\Mustapha\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\Mustapha\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\Mustapha\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\Mustapha\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Mustapha\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 79

**Comment by Izbflsbdvwz** [comment]
@ES-Nighty Change la version de chromedriver dans lib https://chromedriver.chromium.org/downloads

**Comment by ghost** [comment]
my dude im running on linux here could fix a lot of those mistakes but now im stuck on XRANGE

No JSON object could be decoded")
ValueError: No JSON object could be decoded
now i have this, all other from above are fixed

**Comment by raphaelbleier** [comment]
Yeah i also stuck on No object error, but can the programmer help us pls?

**Comment by edcarSky** [comment]
mine not working...

C:\Python27>pip install requests
Traceback (most recent call last):
  File "runpy.py", line 192, in _run_module_as_main
  File "runpy.py", line 85, in _run_code
  File "C:\python-3.8\Scripts\pip.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'pip'

C:\Python27>pip install selenium
Traceback (most recent call last):
  File "runpy.py", line 192, in _run_module_as_main
  File "runpy.py", line 85, in _run_code
  File "C:\python-3.8\Scripts\pip.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'pip'

C:\Python27>pip install colorama
Traceback (most recent call last):
  File "runpy.py", line 192, in _run_module_as_main
  File "runpy.py", line 85, in _run_code
  File "C:\python-3.8\Scripts\pip.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'pip'


C:\Python27\YouTubeShop-master>python yt.py
Traceback (most recent call last):
  File "yt.py", line 1, in <module>
    from lib.multi import Threader
ModuleNotFoundError: No module named 'lib'

even i change path python folders, the same error
