### ISSUE TITLE
Can you help me?

### ISSUE THREAD

**Issue by adamsetiaji** [BitTheByte/YouTubeShop#54]
>>> ===================================================== <<<
 >>>                                                       <<<
 >>>      __   _______   ____  _   _  ___  ____            <<<
 >>>      \ \ / |_   _| / ___|| | | |/ _ \|  _ \           <<<
 >>>       \ V /  | |   \___ \| |_| | | | | |_) |          <<<
 >>>        | |   | |    ___) |  _  | |_| |  __/           <<<
 >>>        |_|   |_|   |____/|_| |_|\___/|_|              <<<
 >>>                                                       <<<
 >>> ===================================================== <<<
 >>> [DEV] : BitTheByte (Ahmed Ezzat)                      <<<
 >>> [GitHub] : https://www.github.com/bitthebyte          <<<
 >>> +++++++++++++++++++++++++++++++++++++++++++++++++++++ <<<
               [!] Version::local  - 12.8.3v
               [!] Version::github - 12.8.3v

[Q] Choose an option (l=like , s=subscribe): s
[I] Selected->Actions::Subscribe
[Q] Set number of threads [Recommended: 10]: 10
[I] Threads = 10
[Q] Enter accounts[Email:Password] file path: accounts.txt
[Q] Enter action file path: actions.txt
[CORE]: Handing off botguard.js execution to chrome

DevTools listening on ws://127.0.0.1:4505/devtools/browser/606bd7e7-e9ac-4f88-a640-e5086bdaa09c
Exception in thread YT_THREAD:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "yt.py", line 72, in subscribe_wrapper
    session = youtube_session(email, password)
  File "yt.py", line 49, in youtube_session
    google = authenticator.Glogin()
  File "C:\Users\muham\YouTubeShop\lib\auth.py", line 130, in Glogin
    token=self.__g_token(),
  File "C:\Users\muham\YouTubeShop\lib\auth.py", line 83, in __g_token
    return json.loads((response.content).replace(")]}'",""))[0][0][2]
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

[CORE]: shutting down chrome ..  please wait

**Comment by edcarSky** [comment]
me also, pls advise... below is the error

[Q] Choose an option (l=like , s=subscribe): l
[I] Selected->Actions::Like
[Q] Set number of threads [Recommended: 10]: 1000
[I] Threads = 1000
[Q] Enter accounts[Email:Password] file path: accounts.txt
[Q] Enter action file path: actions.txt
[CORE]: Handing off botguard.js execution to chrome
[4524:16128:1006/114635.013:ERROR:configuration_policy_handler_list.cc(90)] Unknown policy: Update
[4524:16128:1006/114635.166:ERROR:configuration_policy_handler_list.cc(90)] Unknown policy: Update

DevTools listening on ws://127.0.0.1:54120/devtools/browser/64d24906-91c1-47b0-ac63-b372c47e700b
Traceback (most recent call last):
  File "yt.py", line 98, in <module>
    threader.finish_all()
  File "C:\Python27\YouTubeShop-master\lib\multi.py", line 34, in finish_all
    for _ in xrange(self.q.qsize()): self.__t()
NameError: name 'xrange' is not defined

**Comment by syedbaba141** [comment]
please help


 >>> ===================================================== <<<
 >>>                                                       <<<
 >>>      __   _______   ____  _   _  ___  ____            <<<
 >>>      \ \ / |_   _| / ___|| | | |/ _ \|  _ \           <<<
 >>>       \ V /  | |   \___ \| |_| | | | | |_) |          <<<
 >>>        | |   | |    ___) |  _  | |_| |  __/           <<<
 >>>        |_|   |_|   |____/|_| |_|\___/|_|              <<<
 >>>                                                       <<<
 >>> ===================================================== <<<
 >>> [DEV] : BitTheByte (Ahmed Ezzat)                      <<<
 >>> [GitHub] : https://www.github.com/bitthebyte          <<<
 >>> +++++++++++++++++++++++++++++++++++++++++++++++++++++ <<<
               [!] Version::local  - 12.8.3v
               [!] Version::github - 12.8.3v


[Q] Choose an option (l=like , s=subscribe): s
[I] Selected->Actions::Subscribe
[Q] Set number of threads [Recommended: 10]:
[I] Using the default threads value
[Q] Enter accounts[Email:Password] file path: accounts.txt
[Q] Enter action file path: actions.txt
[CORE]: Handing off botguard.js execution to chrome

DevTools listening on ws://127.0.0.1:54724/devtools/browser/4974852a-d26a-4e67-a8d5-7e3e5742528b
Traceback (most recent call last):
  File "yt.py", line 26, in <module>
    server   = botgaurd.server_start()
  File "D:\YouTubeShop-master\YouTubeShop-master\lib\auth.py", line 16, in server_start
    self.browser = webdriver.Chrome(executable_path=r"lib\\chromedriver.exe")
  File "C:\Python27\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 79

**Comment by sanjaraliyev904** [comment]
Have you downloaded the chrome driver?

сб, 29 янв. 2022 г. в 08:14, syedbaba141 ***@***.***>:

**Comment by syedbaba141** [comment]
Yes i did but now its changed the error
Its saying baniry error something i will show you to screenshot or send you
full error its saying
