### ISSUE TITLE
[CORE]: Handing off botguard.js execution to chrome error

### ISSUE THREAD

**Issue by Navazmkd** [BitTheByte/YouTubeShop#60]
[CORE]: Handing off botguard.js execution to chrome
Traceback (most recent call last):
  File "c:/Users/admin/Desktop/YouTubeShop-master/yt.py", line 26, in <module>
    server   = botgaurd.server_start()
  File "c:\Users\admin\Desktop\YouTubeShop-master\lib\auth.py", line 16, in server_start
    self.browser = webdriver.Chrome(executable_path=r"lib\\chromedriver.exe")
  File "C:\Python27\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary

PS C:\Users\admin\Desktop\YouTubeShop-master>

**Comment by eliasgetachewc1988** [comment]
update chromedriver to your chrome version installed. download here.
https://chromedriver.chromium.org/downloads
